
# Prevent users from using clocks to feed circuits.
ClockPrevention:
  enabled: true
  # How many ticks must pass between signals?
  ticksPerChange: 5

# Colors of the different components.
Colors:
  wire:
    basic:
      r: 21
      g: 66
      b: 66
    powered:
      r: 9
      g: 226
      b: 226
  delay:
    basic:
      r: 21
      g: 66
      b: 66
    powered:
      r: 9
      g: 226
      b: 226
  diode:
    basic:
      r: 21
      g: 66
      b: 66
    powered:
      r: 9
      g: 226
      b: 226
  resistance:
    basic:
      r: 21
      g: 66
      b: 66
    powered:
      r: 9
      g: 226
      b: 226


# DO NOT CHANGE ANYTHING DOWN HERE IF YOU DON'T KNOW WHAT YOU ARE DOING.
Layout:
  0: Circuit0
  1: Circuit1
  2: Circuit2
  3: Circuit3

Debug: false